export const toolbar: string;
export const left: string;
export const right: string;
export const tagContainer: string;
export const tag: string;
export const iconButton: string;
export const alert: string;
export const colorPickerContainer: string;
export const timestamp: string;
